// This file is automatically generated by kanka.mjs
import CombatAction from "../types/CombatAction";
import Item from "../types/Item";

export type ActionTemplate = Omit<CombatAction, "act">;
export const Actions = {
  Bash: {
    name: "Bash",
    tags: [],
    sp: 1,
    targets: { type: "enemy", count: 1, distance: 1, offsets: [0] },
  },
} satisfies Record<string, ActionTemplate>;

export type ItemTemplate = Omit<Item, "action"> & {
  action: keyof typeof Actions;
};
export const Items = {
  GorgothilSword: {
    name: "Gorgothil Sword",
    restrict: ["Cleavesman"],
    slot: "Hand",
    type: "Weapon",
    bonus: {},
    action: "Bash",
    lore: '""May this steel sing the color of heathen blood.""\n\nThis phrase has been uttered ever since Gorgothil was liberated from the thralls of Mullanginan during the Lost War. Gorgothil is now an ever devoted ally, paying their debts by smithing weaponry for all cleavesmen under Cherraphy\'s wing.',
  },
} satisfies Record<string, ItemTemplate>;
