type GameInput =
  | "Forward"
  | "Back"
  | "TurnLeft"
  | "TurnRight"
  | "SlideLeft"
  | "SlideRight"
  | "RotateLeft"
  | "RotateRight"
  | "SwapLeft"
  | "SwapRight"
  | "SwapBehind"
  | "ToggleLog"
  | "Interact"
  | "MenuUp"
  | "MenuDown"
  | "MenuChoose"
  | "Cancel"
  | "OpenStats";
export default GameInput;
