// This file is automatically generated by kanka.mjs
import * as actions from "./actions";
import Item from "./types/Item";

export const GorgothilSword: Item = {
  name: "Gorgothil Sword",
  restrict: ["Cleavesman"],
  slot: "Hand",
  type: "Weapon",
  bonus: {},
  lore: '""May this steel sing the color of heathen blood.""\n\nThis phrase has been uttered ever since Gorgothil was liberated from the thralls of Mullanginan during the Lost War. Gorgothil is now an ever devoted ally, paying their debts by smithing weaponry for all cleavesmen under Cherraphy\'s wing.',
  action: actions.Bash,
};

export const allItems = Object.fromEntries(
  [GorgothilSword].map((item) => [item.name, item]),
);

export function getItem(s?: string) {
  return s ? allItems[s] : undefined;
}
