// This file is automatically generated by [yarn kanka]
import * as actions from "./actions";
import Item from "./types/Item";

export const GorgothilSword: Item = {
  name: "Gorgothil Sword",
  restrict: ["Cleavesman"],
  slot: "Hand",
  type: "Weapon",
  bonus: {},
  action: actions.Bash,
  lore: `""May this steel sing the color of heathen blood.""

This phrase has been uttered ever since Gorgothil was liberated from the thralls of Mullanginan during the Lost War. Gorgothil is now an ever devoted ally, paying their debts by smithing weaponry for all cleavesmen under Cherraphy's wing.`,
};

export const Halberdigan: Item = {
  name: "Halberdigan",
  restrict: ["Martialist"],
  slot: "Hand",
  type: "Weapon",
  bonus: {},
  action: actions.Thrust,
  lore: `In times of peace, halberdigans were simply a tool for picking the fruits of the Ilbombora trees that littered Haringlee's countryside. A devastating fire set by Nightjar's residents and an ensuing drought was punishing enough that farmers began taking up martialism in the name of Cherraphy, in the hope that she'll restore the Ilbombora fields to their former glory.`,
};

export const HalflightCowl: Item = {
  name: "Halflight Cowl",
  restrict: ["Martialist"],
  slot: "Body",
  type: "Armor",
  bonus: {},
  action: actions.Flight,
  lore: `Commonly mistaken as a half light cowl. This cowl instead is named after Halfli's Flight, an ancient martialist technique that requires such speed and precision it gives off the appearance that it's user is flying. Though many martialists don this cowl, few are capable of performing Halfli's Flight to it's full potential.`,
};

export const HaringleeKasaya: Item = {
  name: "Haringlee Kasaya",
  restrict: ["Martialist"],
  slot: "Body",
  type: "Armor",
  bonus: {},
  action: actions.Parry,
  lore: `Traditional garb worn by martialist masters of Haringlee, they are awarded only to those that spend their lives in devotion to the practices of spirtuality. The kasaya symbolizes the wholeness and total mastery of one's self, and one who's inner eye sees only their purpose in life.`,
};

export const KhakkaraOfGhanju: Item = {
  name: "Khakkara of Ghanju",
  restrict: ["Martialist"],
  slot: "Hand",
  type: "Weapon",
  bonus: {},
  action: actions.Sweep,
  lore: `Ghanju is known simply as the first martialist, and the clanging of his khakkhara began and ended many wars. History has stricken his name from most texts, however, as it's said Ghanju practiced neither under Cherraphy or Mullanginan's teachings, nor those of any other God.`,
};

export const LastEyeOfRaong: Item = {
  name: "Last Eye of Raong",
  restrict: ["Martialist"],
  slot: "Special",
  type: "Artefact",
  bonus: {},
  action: actions.Chakra,
  lore: `In all essence, sense. Sight to view actions, sound to hear verse. All senses are owed to Raong, whom may only witness the world of Telnoth through this lens so viciously plucked from it's being in the primordial age.`,
};

export const LoromaysHand: Item = {
  name: "Loromay's Hand",
  restrict: ["Martialist"],
  slot: "Special",
  type: "Artefact",
  bonus: {},
  action: actions.Mudra,
  lore: `In all essence, an end. Gestures and actions performed, repeated through infinite motion. All motion and form finds an ending from Loromay, the primordial deathbed of all things and where even the actions of Gods become meaningless.`,
};

export const NundarialVestments: Item = {
  name: "Nundarial Vestments",
  restrict: ["Martialist"],
  slot: "Body",
  type: "Armor",
  bonus: {},
  action: actions.Brace,
  lore: `On the day of Nundariel's passing, it's said everyone wore these vestments at Cherraphy's order, to "honor a fool's futility". Historians wager this is in reference to Nundarial spending their lifetime weathering attacks behind closed doors, never striking back, forever without purpose, sleeping in the dulcet cradle of war.`,
};

export const Penduchaimmer: Item = {
  name: "Penduchaimmer",
  restrict: ["Martialist"],
  slot: "Hand",
  type: "Weapon",
  bonus: {},
  action: actions.DuoStab,
  lore: `Comprised of two anchors and bound together by threaded fiber plucked from spidokans, these traditional weapons of a martialist are built to stretch and spin much like the hands of a suspended gravity clock. Penduchaimmers are a reminder to all martialists that time will always find it's way back to the living, only in death does it cease.`,
};

export const YamorolsMouth: Item = {
  name: "Yamorol's Mouth",
  restrict: ["Martialist"],
  slot: "Special",
  type: "Artefact",
  bonus: {},
  action: actions.Mantra,
  lore: `In all essence, a beginning. Words spoken aloud, repeated in infinite chanting verse. All words and meanings find a beginning from Yamorol, the primordial birthplace of all things and where even the spirits of Gods are born.`,
};

export const allItems = Object.fromEntries(
  [
    GorgothilSword,
    Halberdigan,
    HalflightCowl,
    HaringleeKasaya,
    KhakkaraOfGhanju,
    LastEyeOfRaong,
    LoromaysHand,
    NundarialVestments,
    Penduchaimmer,
    YamorolsMouth,
  ].map((item) => [item.name, item]),
);

export function getItem(s?: string) {
  return s ? allItems[s] : undefined;
}
